In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/fake-and-real-news-dataset/True.csv
/kaggle/input/fake-and-real-news-dataset/Fake.csv

In [7]:
truenews = pd.read_csv('/kaggle/input/fake-and-real-news-dataset/True.csv')
fakenews = pd.read_csv('/kaggle/input/fake-and-real-news-dataset/Fake.csv')

In [8]:
fakenews.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [9]:
truenews.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [10]:
fakenews.describe()

,title,text,subject,date
count,23481,23481,23481,23481
unique,17903,17455,6,1681
top,MEDIA IGNORES Time That Bill Clinton FIRED His...,,News,"May 10, 2017"
freq,6,626,9050,46

In [11]:
truenews.describe()

,title,text,subject,date
count,21417,21417,21417,21417
unique,20826,21192,2,716
top,Factbox: Trump fills top jobs for his administ...,(Reuters) - Highlights for U.S. President Dona...,politicsNews,"December 20, 2017"
freq,14,8,11272,182

In [12]:
truenews['True/Fake']='True'
fakenews['True/Fake']='Fake'

In [13]:
# Combine the 2 DataFrames into a single data frame
news = pd.concat([truenews, fakenews])
news["Article"] = news["title"] + news["text"]
news.sample(frac = 1) #Shuffle 100%

,title,text,subject,date,True/Fake,Article
19085,Merkel hangs on to power but bleeds support to...,BERLIN (Reuters) - German Chancellor Angela Me...,worldnews,"September 23, 2017",True,Merkel hangs on to power but bleeds support to...
11780,#BoycottStarbucks…CEO Puts Leftist Agenda Over...,"Starbucks has pledged to hire 10,000 refugees ...",politics,"Jan 30, 2017",Fake,#BoycottStarbucks…CEO Puts Leftist Agenda Over...
14096,"FIRST It Was”Low Energy Jeb” And “Lyin Ted,” T...",What do you think about Hillary s new nickname...,politics,"Apr 17, 2016",Fake,"FIRST It Was”Low Energy Jeb” And “Lyin Ted,” T..."
739,Tax-cut debate in U.S. Congress swings to Sena...,WASHINGTON (Reuters) - A U.S. Senate tax-cut b...,politicsNews,"November 8, 2017",True,Tax-cut debate in U.S. Congress swings to Sena...
17801,YIKES! ACADEMY AWARD WINNING Actor Starring In...,Batman fans who have been looking forward to t...,left-news,"Oct 17, 2017",Fake,YIKES! ACADEMY AWARD WINNING Actor Starring In...
...,...,...,...,...,...,...
1775,Trump likely to visit China during November As...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"September 12, 2017",True,Trump likely to visit China during November As...
14615,Cambodia's main opposition party dissolved by ...,PHNOM PENH (Reuters) - Cambodia s highest cour...,worldnews,"November 16, 2017",True,Cambodia's main opposition party dissolved by ...
6008,Trump names Cheryl LaFleur acting chairman of ...,(Reuters) - President Donald Trump on Thursday...,politicsNews,"January 26, 2017",True,Trump names Cheryl LaFleur acting chairman of ...
4934,Trump Contradicts Himself In Latest Whiny Twe...,"In case you haven t noticed, because maybe you...",News,"August 23, 2016",Fake,Trump Contradicts Himself In Latest Whiny Twe...
2603,"Kushner, in statement, says 'I did not collude...",WASHINGTON (Reuters) - President Donald Trump’...,politicsNews,"July 24, 2017",True,"Kushner, in statement, says 'I did not collude..."

In [14]:
#Data Cleaning
from nltk.corpus import stopwords
import string

In [15]:
def process_text(s):

    # Check string to see if they are a punctuation
    nopunc = [char for char in s if char not in string.punctuation]

    # Join the characters again to form the string.
    nopunc = ''.join(nopunc)
    
    # Convert string to lowercase and remove stopwords
    clean_string = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    return clean_string

In [16]:
# Tokenize the Article
#rerun, takes LOOOONG
news['Clean Text'] = news['Article'].apply(process_text)

In [17]:
news.sample(5)

,title,text,subject,date,True/Fake,Article,Clean Text
7923,Iowa Voters Couldn’t Tell The Difference Betw...,It can likely be said that Iowa is one of the ...,News,"February 22, 2016",Fake,Iowa Voters Couldn’t Tell The Difference Betw...,"[Iowa, Voters, Couldn’t, Tell, Difference, Ben..."
8730,"A festival air, and unease, hang over pre-conv...","CLEVELAND (Reuters) - East 4th Street, emblema...",politicsNews,"July 17, 2016",True,"A festival air, and unease, hang over pre-conv...","[festival, air, unease, hang, preconvention, C..."
15814,Iraqi forces capture Akkas gas field from Isla...,BAGHDAD (Reuters) - Iraqi forces captured the ...,worldnews,"November 2, 2017",True,Iraqi forces capture Akkas gas field from Isla...,"[Iraqi, forces, capture, Akkas, gas, field, Is..."
6924,Former astronaut Buzz Aldrin to stay in New Ze...,WELLINGTON (Reuters) - Former U.S. astronaut B...,politicsNews,"December 4, 2016",True,Former astronaut Buzz Aldrin to stay in New Ze...,"[Former, astronaut, Buzz, Aldrin, stay, New, Z..."
16468,BREAKING: Did Hillary’s Unsecured CLASSIFIED E...,Will the State Department ever tell the truth ...,Government News,"Aug 8, 2016",Fake,BREAKING: Did Hillary’s Unsecured CLASSIFIED E...,"[BREAKING, Hillary’s, Unsecured, CLASSIFIED, E..."

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
bow_transformer = CountVectorizer(analyzer=process_text).fit(news['Clean Text'])

print(len(bow_transformer.vocabulary_)) #Total vocab words

39099

In [25]:
#Bag-of-Words (bow) transform the entire DataFrame of text
news_bow = bow_transformer.transform(news['Clean Text'])

In [27]:
print('Shape of Sparse Matrix: ', news_bow.shape)
print('Amount of Non-Zero occurences: ', news_bow.nnz)

Shape of Sparse Matrix:  (44898, 39099)
Amount of Non-Zero occurences:  44898

In [28]:
sparsity = (100.0 * news_bow.nnz / (news_bow.shape[0] * news_bow.shape[1]))
print('sparsity: {}'.format(round(sparsity)))

sparsity: 0

In [29]:
#TF-IDF

In [30]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer().fit(news_bow)
news_tfidf = tfidf_transformer.transform(news_bow)
print(news_tfidf.shape)

(44898, 39099)

In [31]:
#Train Naive Bayes Model
from sklearn.naive_bayes import MultinomialNB
fakenews_detect_model = MultinomialNB().fit(news_tfidf, news['True/Fake'])

In [32]:
#Model Evaluation
predictions = fakenews_detect_model.predict(news_tfidf)
print(predictions)

['True' 'True' 'True' ... 'Fake' 'Fake' 'Fake']

In [33]:
from sklearn.metrics import classification_report
print (classification_report(news['True/Fake'], predictions))

              precision    recall  f1-score   support

        Fake       1.00      1.00      1.00     23481
        True       1.00      1.00      1.00     21417

    accuracy                           1.00     44898
   macro avg       1.00      1.00      1.00     44898
weighted avg       1.00      1.00      1.00     44898

In [35]:
from sklearn.model_selection import train_test_split

news_train, news_test, text_train, text_test = train_test_split(news['Article'], news['True/Fake'], test_size=0.3)

print(len(news_train), len(news_test), len(news_train) + len(news_test))

31428 13470 44898

In [36]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('bow', CountVectorizer(analyzer=process_text)),  
    ('tfidf', TfidfTransformer()),  
    ('classifier', MultinomialNB()),  
])
pipeline.fit(news_train,text_train)

Pipeline(memory=None,
         steps=[('bow',
                 CountVectorizer(analyzer=<function process_text at 0x7ff43feaa6a8>,
                                 binary=False, decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('classifier',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [37]:
prediction = pipeline.predict(news_test)

In [38]:
print(classification_report(prediction,text_test))

              precision    recall  f1-score   support

        Fake       0.96      0.98      0.97      6905
        True       0.98      0.95      0.97      6565

    accuracy                           0.97     13470
   macro avg       0.97      0.97      0.97     13470
weighted avg       0.97      0.97      0.97     13470